version: '3.8'
services:
  captcha-backed:
    build: ./Backend
    container_name: capcha-backend
  nginx:
    build: ./Frontend
    image: nginx:latest
    container_name: capcha-webserver
    restart: always
    volumes:
    - ./Frontend:/usr/share/nginx/html


  
